version: '3.6'
services:
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    container_name: myredis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
    environment: 
      - ENV=develop
    env_file:
      - redis.env