version: '3.6'
services:
  docker-swagger:
    image: app
    build: .
    healthcheck:
      test: curl -fs http://localhost:3000/api/stocks || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      NODE_ENV: production
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - .:/usr/src/app
 