version: '3.6'
services:
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    container_name: myredis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
    env_file:
      - redis.env
  db:
    image: "mariadb:10.5.3"
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./test.sh:/tmp/test.sh
    env_file:
      - sql.env