version: '3.6'
services:
  docker-swagger:
    image: app
    build: .
    depends_on:
       - "redis"
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      NODE_ENV: production
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - .:/usr/src/app
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    container_name: myredis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
    environment: 
      - ENV=develop
    env_file:
      - redis.env